### PR TITLE
Add recipe for elimc

### PR DESCRIPTION
**Pull request by Matvii-Jarosh**
### Brief summary of what the package does

This is a simple TUI application for calculating mathematical problems using infix and rpn

### Direct link to the package repository

https://github.com/Matvii-Jarosh/elimc

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `elimc.el` with byte-compile using Emacs 29.4:
```
elimc.el:447:6: Warning: the function `cl-subseq' might not be defined at runtime.
elimc.el:380:10: Warning: the function `widget-value-set' might not be defined at runtime.
```

⸺ `elimc.el` with package-lint 20250212.1515:
```
6 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: error: There is no (provide 'elimc) form.
1:65: warning: You should depend on (emacs "24.1") if you need lexical-binding.
447:5: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-subseq'.
451:5: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-subseq'.
567:3: error: You should depend on (emacs "24.1") if you need `isnan'.
```

**Comment by riscy** [comment]
No problem.  I might suggest trying to update package-lint and see if that works.  In the meantime, here's the latest -

⸺ `elimc.el` with byte-compile using Emacs 30.1:
```
elimc.el:42:11: Warning: Package cl is deprecated
In end of data:
elimc.el:384:10: Warning: the function `widget-value-set' might not be defined at runtime.
```
Needs a `(require 'wid-edit)`

⸺ `elimc.el` with package-lint 20250228.1322:
```
2 issues found:
1:0: error: There is no (provide 'elimc) form.
9:21: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
```

**Comment by riscy** [comment]
> I have a compilation error in package-lint

No problem - check the latest version, which may have a fix for your case?

In the meantime --

⸺ `elimc.el` with byte-compile using Emacs 30.1:
```
elimc.el:42:11: Warning: Package cl is deprecated
```

⸺ `elimc.el` with package-lint 20250307.912:
```
2 issues found:
9:21: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
9:38: warning: Version dependency for cl-lib appears too high: try 0.7.1
```

**Comment by Matvii-Jarosh** [comment]
oh, what nonsense is it to use Windows, it's the worst operating system, half of everything doesn't work in it. I've tried a lot but I don't have anything about the fact that there is an error or warning in the code. In short, screw it all, whoever needs it will find this project on the Internet

**Comment by riscy** [comment]
Don't worry - we can hit pause here and you can feel free to reopen a PR for this or any other package in the future.  (I agree, my past experience with Windows + Emacs wasn't ideal, but I'm sure you'll find a way.)
