### PR TITLE
SDML source modes

### PR DESCRIPTION
**Pull request by johnstonskj**
### Brief summary of what the package does

This is a set of four related packages that support Simple Domain Modeling Language (SDML) editing.

### Direct link to the package repository

https://github.com/johnstonskj/emacs-sdml-mode

### Your association with the package

I am the author and maintainer

### Relevant communications with the upstream package maintainer

package-lint naming errors in sdml-mode in sdml-ispell because packages I depend upon use a name resolution trick to include definitions.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for these.  Quick first pass --

`flycheck-sdml.el` with byte-compile using Emacs 28.1:
```
flycheck-sdml.el:161:33: Warning: reference to free variable
    `tree-sitter-language'
flycheck-sdml.el:170:38: Warning: reference to free variable
    `tree-sitter-tree'
In flycheck-sdml--start:
flycheck-sdml.el:180:38: Warning: Unused lexical argument `checker'
```
I think the dependency on tree-sitter is missing in the Package-Requires, here.

`flycheck-sdml.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- flycheck-sdml.el#L186: It's safer to sharp-quote function names; use `#'`
```

---------------

`ob-sdml.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ob-sdml.el#L82: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```

---------------

`sdml-ispell.el` with byte-compile using Emacs 28.1:
```
sdml-ispell.el:53:1: Error: Cannot open load file: No such file or directory, sdml-mode
```
(You can disregard since this dependency isn't yet on MELPA)

`sdml-ispell.el` with package-lint 20230525.1346:
```
2 issues found:
7:38: error: Package sdml-mode is not installable.
61:0: error: "tree-sitter-ispell-sdml-text-mapping" doesn't start with package's prefix "sdml-ispell".
```

-----------------

`sdml-mode.el` with byte-compile using Emacs 28.1:
```
sdml-mode.el:445:19: Warning: reference to free variable `ts-fold-range-alist'
sdml-mode.el:445:19: Warning: assignment to free variable
    `ts-fold-range-alist'
sdml-mode.el:449:40: Warning: reference to free variable `ts-fold-indicators'
In end of data:
sdml-mode.el:450:8: Warning: the function `ts-fold-indicators-mode' is not
    known to be defined.
sdml-mode.el:447:6: Warning: the function `ts-fold-line-comment-mode' is not
    known to be defined.
sdml-mode.el:446:6: Warning: the function `ts-fold-mode' is not known to be
    defined.
```


`sdml-mode.el` with package-lint 20230525.1346:
```
3 issues found:
121:0: error: "tree-sitter-hl-face:type.scope" doesn't start with package's prefix "sdml".
121:0: error: `tree-sitter-hl-face:type.scope' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
261:0: error: "tree-sitter-indent-sdml-scopes" doesn't start with package's prefix "sdml".
```
(Let me know if these are tree-sitter standards that I should become accustomed to)

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by johnstonskj** [comment]
Well that's a lot more than I expected! Thanks very much, this is super
helpful.

Simon Johnston
***@***.***
OpenGPG: 644C F778 29C7 C3BB 5B86 8DC8 96A0 664B 9D48 2667

**Comment by johnstonskj** [comment]
I've made all the changes in the package repository. I've put better comments close to the naming convention errors, these are all due to requirements of downstream packages. Not sure I would say they are standards and with Emacs 29 tree sitter being built-in I would hope some of these would go away.

**Comment by riscy** [comment]
Thanks for accommodating.

I probably should have suggested we move this into at least two PRs so that we can test dependency installation automatically, but I've checked carefully and I think we're good there.

I have some lingering concerns with this variable that package-lint nags about:
```
121:0: error: "tree-sitter-hl-face:type.scope" doesn't start with package's prefix "sdml".
```
What ties `tree-sitter-hl-face:type.scope` uniquely to sdml mode?  Or, in other words, what is to stop another package from introducing a `tree-sitter-hl-face:type.scope` variable, leading to a namespace conflict?

**Comment by johnstonskj** [comment]
Ah, I should document that. Basically the underlying package runs
tree-sitter queries over some source which returns a node+scope pair, the
scope name is appended after the ":" and used to look up a face. Would be
way nicer if there was a lookup function but there isn't.

Simon Johnston
***@***.***
OpenGPG: 644C F778 29C7 C3BB 5B86 8DC8 96A0 664B 9D48 2667

**Comment by riscy** [comment]
I'm not deeply familiar with tree-sitter-hl (the underlying package you're referring to) but I think I understand 'the scope name is appended after the ":" and used to look up a face'.  But I still don't see what ties `tree-sitter-hl-face:type.scope` uniquely to sdml-mode.

Is this an accurate rephrasing?:  SDML mode has some language feature that makes highlighting "type scopes" a valuable thing to do.  tree-sitter-hl does not implement this highlighting type.  As a shortcut, it has been added here as part of sdml-mode.

The reason I am concerned about this (as I would be for any other package -- namespaces are one of the biggest things we look out for, since Emacs doesn't have strong facilities for this) is that it looks like you're adding a feature into tree-sitter-hl's "protected" namespace.  Other packages besides SDML mode may want to do the same thing in the future.  If tree-sitter-hl itself were to add this feature, it would clash with your package.  The better outcome would be for tree-sitter-hl to add this itself, rather than you implementing it here on the side.

**Comment by riscy** [comment]
Friendly ping :)

**Comment by johnstonskj** [comment]
I know it's been a long time, I have simplified the SDML repo and split the sub-modes out into their own packages to add later. The stand-alone mode is now on it's own in this PR.

**Comment by riscy** [comment]
Hi again, and no worries.   Here's a quick pass of the latest --


`sdml-mode-hl.el` with byte-compile using Emacs 29.3:
```
sdml-mode-hl.el:347:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```


Package and license:
- Prefer equivalent recipe: `(sdml-mode :repo "sdm-lang/emacs-sdml-mode" :fetcher github)`
- There is a mix of MIT and Apache 2.0 licenses (see below) and the API is detecting your license as  "Other"; for the API, try to use a standard license file format

The different licenses:
- MIT License -- sdml-mode-abbrev.el: Abbreviation Support
- MIT License -- sdml-mode-cli.el: CLI integration
- MIT License -- sdml-mode-hl.el: Highlighting Support
- MIT License -- sdml-mode-indent.el: Indentation Support
- Apache License 2.0 -- sdml-mode.el: Major mode for SDML

**Comment by riscy** [comment]
I'm not sure which comment you're referring to, but it seems like you solved all of the nags in any case.

More recently I've been recommending the following (when they make sense), but these are minor and non-blocking:

- sdml-mode-cli.el#L76: You may want to prefer `(derived-mode-p 'xyz)`
- sdml-mode.el#L185: You may want to prefer `(derived-mode-p 'xyz)`
- sdml-mode.el#L202: You may want to prefer `(derived-mode-p 'xyz)`

**Comment by johnstonskj** [comment]
Thanks for all the help! I will look at the derived-mode-p suggestions!
