### PR TITLE
Add recipe for alabaster-themes

### PR DESCRIPTION
**Pull request by vedang**
### Brief summary of what the package does

A collection of minimal light and dark themes for GNU Emacs based on the original Sublime Text Alabaster color scheme.

### Direct link to the package repository

https://github.com/vedang/alabaster-themes

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  There is some careful naming that multi-theme packages have to adhere to.  There's an entry on this on a WIP FAQ that you can access here: https://github.com/melpa/melpa/blob/faq/FAQ.md

In the meantime, quick first pass (themes aren't typically compiled, but doing so points to some issues with the dependency tree):

⸺ `alabaster-themes.el` with byte-compile using Emacs 30.1:
```
alabaster-themes.el:194:78: Warning: reference to free variable `alabaster-themes-faces'
alabaster-themes.el:195:45: Warning: reference to free variable `alabaster-themes-custom-variables'
In alabaster-themes--heading:
alabaster-themes.el:1159:17: Warning: reference to free variable `alabaster-themes-no-bold'
```

⸺ `alabaster-theme.el` with byte-compile using Emacs 30.1:
```
alabaster-theme.el:196:2: Error: Symbol's value as variable is void: alabaster-palette
```

⸺ `alabaster-mono-theme.el` with byte-compile using Emacs 30.1:
```
alabaster-mono-theme.el:196:2: Error: Symbol's value as variable is void: alabaster-mono-palette
```

⸺ `alabaster-dark-theme.el` with byte-compile using Emacs 30.1:
```
alabaster-dark-theme.el:196:2: Error: Symbol's value as variable is void: alabaster-dark-palette
```

⸺ `alabaster-dark-mono-theme.el` with byte-compile using Emacs 30.1:
```
alabaster-dark-mono-theme.el:196:2: Error: Symbol's value as variable is void: alabaster-dark-mono-palette
```

⸺ `alabaster-bg-theme.el` with byte-compile using Emacs 30.1:
```
alabaster-bg-theme.el:353:2: Error: Symbol's value as variable is void: alabaster-bg-palette
```

⸺ Package and license:
- Avoid `:branch` in recipes except in unusual cases (we'll pull from your default branch, which I think should just be `main` anyway?)

**Comment by vedang** [comment]
Thanks for the review, I'll make the changes and resubmit

**Comment by vedang** [comment]
I've updated the themes package, as well as the recipe, based on your feedback.

**Comment by riscy** [comment]
Thank you.  Here's the latest -

⸺ `alabaster-themes.el` with byte-compile using Emacs 30.1:
```
alabaster-themes.el:195:78: Warning: reference to free variable `alabaster-themes-faces'
alabaster-themes.el:196:45: Warning: reference to free variable `alabaster-themes-custom-variables'
In alabaster-themes--heading:
alabaster-themes.el:1160:17: Warning: reference to free variable `alabaster-themes-no-bold'
```

**Comment by vedang** [comment]
Hi @riscy : 

I am running the command:
```
emacs --batch -L . --eval "(setq byte-compile-error-on-warn nil)" -f batch-byte-compile *.el
```
to check for byte compilation errors, and I'm not seeing any errors. How are you generating these warnings?

**Comment by vedang** [comment]
In any case, I have moved the definitions of those variables before their first use in the alabaster-themes.el file, hopefully resolving this issue. 

Do let me know how to run this check for future reference.

**Comment by riscy** [comment]
Thank you!

> Do let me know how to run this check for future reference.

I have a set of scripts I run here - https://github.com/riscy/melpazoid

You mention you're running -
```bash
emacs --batch -L . --eval "(setq byte-compile-error-on-warn nil)" -f batch-byte-compile *.el
```
but if you include `-Q` (or at least `-q`) in this, it won't load your personal init.  Your personal init is probably defining variables that a cleanroom byte-compile won't have available.

I currently see -

⸺ `alabaster-themes.el` with byte-compile using Emacs 30.1:
```
alabaster-themes.el:214:78: Warning: reference to free variable `alabaster-themes-faces'
```
But *this* one appears to be a [wrong time](https://www.gnu.org/software/emacs/manual/html_node/elisp/Problems-with-Macros.html#Problems-with-Macros) bug in the code, which is happening because Emacs attempts to expand/evaluate macros before it gets to anything else (in this case, evaluating the `defgroup` form).

**Comment by vedang** [comment]
Hmm .. the issue here is not immediately obvious to me, and I'm not able to reproduce it locally. I cannot run melpazoid locally at the moment, and `emacs --batch -Q -L . --eval "(setq byte-compile-error-on-warn nil)" -f batch-byte-compile *.el` does not throw any errors. 

I'd really appreciate getting this merged in! The theme is working fine for me for a few months now, and I am blocked on how to proceed.

**Comment by riscy** [comment]
> `emacs --batch -Q -L . --eval "(setq byte-compile-error-on-warn nil)" -f batch-byte-compile *.el` does not throw any errors.

It took me a minute but I think I've reproduced what you're seeing, and it's because the specific order you happen to be compiling the files in (`*.el` expands in lexicographic order) works.  But if I choose one file by itself:

```bash
$ emacs --batch -Q -L . -f batch-byte-compile alabaster-themes.el
In alabaster-themes-theme:
alabaster-themes.el:214:78: Warning: reference to free variable ‘alabaster-themes-faces’
```
or even just reverse the order:
```bash
$ emacs --batch -Q -L . -f batch-byte-compile $(ls -r *.el)
In alabaster-themes-theme:
alabaster-themes.el:214:78: Warning: reference to free variable ‘alabaster-themes-faces’
```
we arrive at the same warning.  I don't fault you for this or anything - these are the sorts of "works on *my* computer" idiosyncrasies I try to check for (and sort out with melpazoid - although I realize it isn't the easiest to get setup with).

Fortunately this is easier to solve than I thought - just move your `(defmacro alabaster-themes-theme ...` *underneath* your `(defvar alabaster-themes-faces` so that the `defvar` occurs before the `defmacro`.

Some other minor checks (that I've only just started running), mostly fyi:

- alabaster-themes.el:5:10: To get `(lm-authors)` to work, write `;; Author: Your Name <email/url/@handle>`
- alabaster-themes.el:6:14: To get `(lm-maintainers)` to work, write `;; Maintainer: Your Name <email/url/@handle>`

(and same with the other files, but not a blocker)

**Comment by vedang** [comment]
Thank you! I've made both changes and pushed them. I'll update my notes to ensure that I batch compile individually, or in different order, next time onwards.

**Comment by riscy** [comment]
Thank you!
