### PR TITLE
Add empv-hydra & exclude it from empv recipe

### PR DESCRIPTION
**Pull request by isamert**
### Brief summary of what the package does

This adds hydra extension for empv. See #8314 for details about empv.

### Direct link to the package repository

https://github.com/isamert/empv.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

---

This fixes isamert/empv.el#97.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  You mentioned in the [linked issue](https://github.com/isamert/empv.el/issues/97) that `with-eval-after-load` causes issues, but I bet those could be fixed with a `declare-function` at the top, which might be a less-drastic change for your users.  I feel like the hydra just on its own is almost like indexing configuration, which we tend to stay away from in the MELPA index.

⸺ `empv.el` with byte-compile using Emacs 30.1:
```
empv.el:835:2: Warning: docstring wider than 80 characters
In empv--consult-get-input-with-suggestions:
empv.el:2619:10: Warning: Unused lexical variable `consult-async-split-style'
In empv-bookmark-jump:
empv.el:3030:20: Warning: Unused lexical variable `kind'
In end of data:
empv.el:707:43: Warning: the function `im-to-keyword' is not known to be defined.
```

⸺ `empv.el` with package-lint 20250324.1912:
```
1 issue found:
3374:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

⸺ `empv.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- empv.el#L1765: There is no need to quote lambdas (neither #' nor ')
- empv.el#L1951: It's safer to sharp-quote function names; use `#'`
- empv.el#L1864: This double negation can be collapsed (`not` aliases `null`)
- empv.el#L2155: You may want to consider `(derived-mode-p 'xyz)`
- empv.el#L2996: You may want to consider `(derived-mode-p 'xyz)`
- empv.el#L3275: You may want to consider `(derived-mode-p 'xyz)`
```

(+ several checkdoc issues that should be looked at, but not a blocker)

**Comment by isamert** [comment]
Fixed the warnings, flymake got disabled due to `trusted-content` change and I thought there were no issues. Also applied the melpazoid suggestions.

---

I guess this one is okay:

```
3374:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```
---

> Thanks for this. You mentioned in the https://github.com/isamert/empv.el/issues/97 that with-eval-after-load causes issues, but I bet those could be fixed with a declare-function at the top, which might be a less-drastic change for your users.

Yes, I would very much like to go with this route but I think `declare-function` won't cut it because `defhydra` is a macro and doing simple `(declare-function defhydra "hydra")` causes all the forms inside the `defhydra` call look like malformed function calls. Unfortunately `defhydra` does not accept quoted forms, so there is no easy fix and the macro itself does all the required logic and there is no simple function alternative from the hydra package. If you have any examples on providing hydra definition with a package without forcing hydra to be installed, I'm all ears.

>  I feel like the hydra just on its own is almost like indexing configuration, which we tend to stay away from in the MELPA index.

I definitely understand this and it makes sense. In this case, this is a ~40 line hydra definition and it's too much for a configuration. But of course if you think MELPA is not the place, I can always move this hydra configuration into README (or some similar place) and suggest users to copy from there to their init file.

**Comment by riscy** [comment]
> Unfortunately defhydra does not accept quoted forms

Falling back on an `eval` would would allow everything to be quoted.  The drawback is that the macro isn't byte-compiled (I think the performance hit would be negligible) and also the byte-compiler won't be able to detect when these functions don't exist (or change names), so you assume some risk without a test:
```elisp
(when (require 'hydra nil t)
  (eval
   '(defhydra
     empv-hydra nil
     "EMPV Hydra."
     ("o" #'empv-play-or-enqueue "play or enqueue"                         :column "Play")
```

Let me know what you think... and while I'm here, I also notice a function in empv.el is missing a def?

⸺ `empv.el` with byte-compile using Emacs 30.1:
```
empv.el:1971:27: Warning: the function `empv-youtube-tabulated' is not known to be defined.
```

**Comment by isamert** [comment]
> Falling back on an `eval` would would allow everything to be quoted. 

I completely forgot about this. Not getting byte-compilation errors is unfortunate but it's not a core functionality and I can _maybe_ write some tests or have a script that un-quotes it and reports the errors in my git commit hooks or something. This is a better solution and I guess we can simply discard this PR. Thanks for your support!

> I also notice a function in empv.el is missing a def?

Fixed this, it was a leftover from an earlier refactor. Interesting that I wasn't getting that compile error.
