### PR TITLE
Add recipe for `denote-regexp`

### PR DESCRIPTION
**Pull request by swflint**
-------

### Brief summary of what the package does

`denote-regexp` provides a function to help generate regular expressions to locate `denote` files, following a user's `denote-file-name-components-order` setting.

### Direct link to the package repository

https://git.sr.ht/~swflint/denote-regexp

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `denote-regexp.el` with byte-compile using Emacs 30.1:
```
denote-regexp.el:221:11: Warning: Unused lexical variable `base-rx'
In end of data:
denote-regexp.el:142:71: Warning: the function `denote-sort-keywords-lessp' is not known to be defined.
```

⸺ `denote-regexp.el` with package-lint 20250307.912:
```
1 issue found:
265:1: error: You should depend on (emacs "27.1") if you need `rx-define'.
```

⸺ `denote-regexp.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- `;;; Commentary` decoration like `;;;;...` will appear downstream
```

**Comment by swflint** [comment]
Thank you for pointing these out.  I've fixed the byte compilation error, the Emacs version error, and the issue with commentary decoration.

**Comment by riscy** [comment]
I have a quick update here - 

⸺ `denote-regexp.el` with byte-compile using Emacs 30.1:
```
denote-regexp.el:142:69: Warning: reference to free variable `denote-sort-keywords-comparison-function'
```

**Comment by swflint** [comment]
Interesting.  It's definitely available in the declared required version of denote.  I'll add a dummy defvar though.

**Comment by riscy** [comment]
Thank you!
